### ISSUE TITLE
Index out of bounds?

### ISSUE THREAD

**Issue by rtpwilliams** [moore-andrew05/FIJI_ImageStitcher9000#7]
Seems to be an issue with the following directory: `/Volumes/WormHole/robert/220712_ELT-2_Regulation_Rep3/ELT2gfp/ELT2rnai`

See below for my output
```
(base) rtpw@beto-mini FrankenStein % java -Xmx14G -jar FrankenStein.jar
Enter Image Directory: /Volumes/WormHole/robert/220712_ELT-2_Regulation_Rep3/ELT2gfp/ELT2rnai
Enter output directory (Stitched images will be saved here): /Volumes/rtpw/Documents/01_RESEARCH/06_NOTEBOOK5/RWP032_ELT-2_Target_Regulation/DV_Data/ELT2gfp/ELT2rnai/REP2

If you are unclear on what to input for image names, see the README on github.

Enter the name of the images (do not include incrementors): 220712_ELT2gfp_ELT2rnai_worm
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at FileReader.cleaner(FileReader.java:57)
	at FileReader.builder(FileReader.java:75)
	at FileReader.looper(FileReader.java:88)
	at Main.main(Main.java:20)
```

my java:
```
(base) rtpw@beto-mini FrankenStein % java -version
java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)
```

**Comment by moore-andrew05** [comment]
Should be fixed now. New refactored release seems to handle everything a lot better and you should have a better time overall. Tested this directory and it ran fine. New release is v0.1.0.
